### ISSUE TITLE
Plugin not working in VLC build 3.0.19

### ISSUE THREAD

**Issue by SpectacularInsanity** [nurupo/vlc-pause-click-plugin#101]
## Checklist

- [ x ] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and the issue still persists.

## Environment

- OS:               Windows 10 Home
- VLC version:      3.0.19
- VLC bitness:      64 bit
- Plugin version:   3.0
- Plugin bitness:   64 bit

The menu options (checkboxes listed in step 3, 4, and 5) Do not appear when placing the .dll in VLC main folder.

### Steps to reproduce

Even after uninstalling and reinstalling VLC, deleting and replacing the .dll file, and rebooting VLC multiple times, the preferences options still did not appear.

The plugin stopped working after VLC updated to 3.0.19. I'm not sure what happened, exactly, but that's the only thing that changed. I tried reinstalling an older version of VLC, but the program keeps auto-updating and I'm not sure I should even bother trying to stop it.

**Comment by nurupo** [comment]
>when placing the .dll in VLC main folder.

That's the wrong folder. It should be placed into `plugins`.

**Comment by nurupo** [comment]
I just tested and the plugin works with 64-bit VLC 3.019 on Windows 10, so you just placed the dll in the wrong folder.

**Comment by SpectacularInsanity** [comment]
My mistake. I thought you were supposed to place it in the main folder. I got it working. Thank you for the clarification!
