### ISSUE TITLE
Does the vlc-pause-click-plugin not allow pausing/playing by clicking on the screen?

### ISSUE THREAD

**Issue by fuxin-mail** [nurupo/vlc-pause-click-plugin#108]
Does the vlc-pause-click-plugin not allow pausing/playing by clicking on the screen?

**Comment by nurupo** [comment]
Huh? Please see the README file, because you got what this plugin does totally backwards.

**Comment by fuxin-mail** [comment]
> 啊？ 请参阅 README 文件，因为您完全了解了该插件的功能。

Thank you! It's fixed successfully
