### ISSUE TITLE
click pause not working

### ISSUE THREAD

**Issue by wqwerc2** [nurupo/vlc-pause-click-plugin#109]
Only full screen feature work
I tried the plugin on both the last x64 vlc version and 3.0 x64 version(from archive) on clean install(removed old preferences)

**Comment by nurupo** [comment]
This is very likely a setup issue on your end, as the plugin works flawlessly on multiple Windows and Linux systems around here and as reported by other users. I'm currently using it on Windows with VLC 3.0.20 without an issue.

Sadly, there is no easy way for me to troubleshoot what went wrong during your plugin setup.

I suggest [going over the usage instructions](https://github.com/nurupo/vlc-pause-click-plugin?tab=readme-ov-file#usage) and making sure you have followed them correctly, checking both checkboxes that enable the plugin.

If you don't see these checkboxes, as well as the plugging settings, as shown in the screenshots, it means that you have installed the plugin incorrectly: either downloaded an incompatible plugin version, or didn't extract the dll out of the zip archive, or put the dll into the wrong directory, or you have multiple VLCs installed and you setup the plugin for another VLC that you don't use, etc. Just start over by following the README and double-check everything you do.

Hope that helps!

**Comment by wqwerc2** [comment]
thanks a lot for the help! my mistake was not enabling the control interfaces checkbox! it's all good now
I highly appreciate your great plugin!

**Comment by nurupo** [comment]
Glad you got it working!
