### ISSUE TITLE
pause click in VLC 2.2.

### ISSUE THREAD

**Issue by radar54** [nurupo/vlc-pause-click-plugin#11]
Hi, 
I'm running Windows 10 x64, VLC v2.2.1 x64, and using the 64 bit version of the plugin.

As can be seen in the picture, the VLC pause-click plugin is installed correctly; however, when I single click on the video, while it is playing, the video does NOT pause.  I did exit and restart VLC after enabling the plugin.  Is this a known issue that the pluging does not work in v2.2.1?  Or, maybe there is something else I must do to install the plugin correctly.  

Thanks

![vlc pause click](https://cloud.githubusercontent.com/assets/16638356/12224147/34bbfd34-b7b7-11e5-8ca1-36f75482a1a1.PNG)

**Comment by nurupo** [comment]
[Per Usage instructions in the README file, there are two check boxes that need to be checked for 2.2.x version of the plugin](https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x%2B#usage). Are both of them checked?

**Comment by radar54** [comment]
Hi,

 

It works!  Thanks very much for getting back to me.  I did not know about the 2nd check box in the Interface section.

 

Thanks again,

Ben
