### ISSUE TITLE
Works for video playback but not for audio

### ISSUE THREAD

**Issue by oblongau** [nurupo/vlc-pause-click-plugin#111]
This works for playback of a video file (VLC 3.0.16 on Linux Mint) but not on playback of an audio file.

Unless I'm missing something I'd like to have the same function for audio files.

**Comment by nurupo** [comment]
See https://github.com/nurupo/vlc-pause-click-plugin?tab=readme-ov-file#it-works-for-videos-but-not-for-audio-only-files

**Comment by nurupo** [comment]
To add to that, the only way for a VLC plugin to learn of the mouse clicks events is via the video filter interface, there is no other way that VLC provides that information. Should probably mention that in the README too.

**Comment by oblongau** [comment]
Excellent... my apologies for not seeing that explanation before posting.

**Comment by nurupo** [comment]
Updated that README section to mention clearly that this is the limitation of VLC and nothing the plugin can do about. https://github.com/nurupo/vlc-pause-click-plugin/commit/86daaa530b92405e163bd6fd1bc7834dd6e59de8

There is a workaround provided at the end of that section I linked earlier btw, if you are cool with the audio visualizers.
