### ISSUE TITLE
Installation unsuccessful. please help.

### ISSUE THREAD

**Issue by 0megaZer0** [nurupo/vlc-pause-click-plugin#12]
I followed all the instructions, step-by-step. downloaded the 64 bit file for windows (which is what I have) Then extracted the file (via winRAR) to the specified path of "{VLC}/plugins/video_filter/" when that didn't work, I went and extracted it again, this time manually finding the path of computer > HPC (C:) > Program Files (x86) > VideoLAN > VLS > plugins > video_filter and placed the file there. 

there's still no check box in the advanced preferences under video filter called "Pause/Play video on mouse click" for me to check. 

I even tried to open the specific file through VLC directly (which is why all the pics next to all the plugin files now have mini-VLC icons next to them instead of the usual gears one)

I don't understand what I've done wrong. please help.

![pause-play plugin](https://cloud.githubusercontent.com/assets/17167147/12961859/2f140912-d008-11e5-9165-302e2a772b08.PNG)

![pause plugin 2](https://cloud.githubusercontent.com/assets/17167147/12961862/368d33bc-d008-11e5-80f6-6fec2c994ea7.PNG)

**Comment by Kasijjuf** [comment]
What version of VLC do you have installed?

**Comment by 0megaZer0** [comment]
2.2.1

**Comment by Kasijjuf** [comment]
Even though you are using 64-bit Windows, it looks like you are using a 32-bit version of VLC (the folder containing VLC's files is "Program Files (x86)" in your screenshot). I'd recommend trying the 32-bit version of the plugin.

**Comment by 0megaZer0** [comment]
that is entirely possible as I wasn't always aware of what bit system I have.... didn't know a 32 bit program *could* even run on a 64 bit system.. hang on...

**Comment by 0megaZer0** [comment]
That did the trick. Thanks, mate. by the by, how did you know I was using a 32 bit program just from that screenshot?

**Comment by Kasijjuf** [comment]
On 64-bit Windows there are two subdirectories in the root directory that contain all the executable files for your installed applications: "Program Files" and "Program Files (x86)".

"Program Files" contains your 64-bit applications.
"Program Files (x86)" contains your 32-bit applications.

At the very top of your first screenshot, the address bar lists you being within "Program Files (x86)".

**Comment by 0megaZer0** [comment]
huh. always wondered why there were 2 separate program file folders. learned something today.

**Comment by Kasijjuf** [comment]
Glad I could help.

Enjoy the plugin and welcome to GitHub

**Comment by nurupo** [comment]
@Kasijjuf thanks for the help!

I will close the issue now that it's resolved.
