### ISSUE TITLE
It's working on ubuntu?

### ISSUE THREAD

**Issue by morppheus** [nurupo/vlc-pause-click-plugin#14]
What the directory in Ubuntu 14.04 ?
and how to download it ready for use here in github ? I am new here lol

**Comment by nurupo** [comment]
Follow the instructions for Debian, they should work for Ubuntu.

**Comment by Kasijjuf** [comment]
@morppheus 
 [https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x%2B#debian](url)
Here are the directions for Ubuntu. I currently have this running on Ubuntu 14.04. If you need any more help just ask me. I'd be happy to try to help you get the plugin installed.

**Comment by nurupo** [comment]
I'm closing this issue as it has been over 7 days since the last reply.
