### ISSUE TITLE
Plugin doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by Pleskan** [nurupo/vlc-pause-click-plugin#18]
Hi!

I already have tested plugin on Ubuntu 16.04 vlc version
from 2.2.2 to 2.2.4 and it doesn't seems to work as expected.
I had been trying vlc from videolan PPA as well as compile and package
vlc myself, but alas it is just not work at all on Ubuntu 16.04 with Unity DE.

Regards!

**Comment by nurupo** [comment]
Did you get any errors when building and installing the plugin?

Did you check both of the the plugin checkboxses in Preferences?

**Comment by Pleskan** [comment]
No, everything was clean, without any kind of errors.
Yes, I strictly followed the installations instruction.
It is just does not work on fresh release of Ubuntu, 
as well as Kubuntu 16.04 in my case

**Comment by nurupo** [comment]
Installed a fresh Ubuntu 16.04 amd64 in a VM, the plugin works just fine. [Here is a video](https://my.mixtape.moe/mnbypp.webm). You are likely just not following the instructions correctly. Kind of wish I could get back my time I have spent on downloading Ubuntu and this testing.

**Comment by Pleskan** [comment]
My mind is a completely blank about the reason of the issue.
I followed the instructions strictly, mate.
Anyway thanks a lot for your time!
Probably, I'll just use SMPlayer on that system.
Regards!

**Comment by Pleskan** [comment]
Your plugin works well on Windows 8.1 x86_64.
So, you can see, that I can switch it on in correct way :-)
May be is something wrong with gcc ABI or any other settings on my Ubuntu
installation, I don't know yet.

**Comment by nurupo** [comment]
Well, nothing I can do if I can't reproduce the behavior.

>I followed the instructions strictly, mate.

Were you using the right version of the plugin? You need to use the one from `vlc-2.2.x+` subdirectory as the VLC in Ubuntu 16.04 package repository is of 2.2.x version.

>May be is something wrong with gcc ABI or any other settings on my Ubuntu
installation, I don't know yet.

Well, try this yourself on a fresh Ubuntu:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo reboot
sudo apt-get install vlc git
git clone https://github.com/nurupo/vlc-pause-click-plugin.git
cd vlc-pause-click-plugin/vlc-2.2.x+
sudo apt-get install build-essential pkg-config libvlccore-dev
make
sudo make install
```

Launch VLC, toggle the two check-boxes, restart VLC and test.

**Comment by Pleskan** [comment]
OK, thanks for a quick response :-)
May be the reason of the issue is a /home dir from my previous installation
with some "dirty" settings.
So, I appreciate your help and I think the issue can be closed as unconfirmed

**Comment by Pleskan** [comment]
It sounds weird, 
but plugin start to work, 
when it was compiled and installed from 
fresh user profile.
Everything is OK for now.

**Comment by nurupo** [comment]
Cool, glad it works. Will keep this issue of dirty /home in mind when someone else will be having issues.

**Comment by Pleskan** [comment]
OK, keep it. 
Despite the fact that it is very rare case.
