### ISSUE TITLE
Plugin works on VLC 2.2.2 and Lubuntu 16.04

### ISSUE THREAD

**Issue by brunocassol** [nurupo/vlc-pause-click-plugin#21]
Just to let you know that the plugin works on Lubuntu 16.04 and VLC 2.2.2.

This is the current default VLC installed from Ubuntu repos using sudo aptp-get install vlc.

![image](https://cloud.githubusercontent.com/assets/203541/24932749/f55748fa-1ee0-11e7-9d45-a58928163665.png)

I just wanted to let you know in case another user reports otherwise.

Thank you for sharing and documenting this.

**Comment by nurupo** [comment]
Cool, thanks.
