### ISSUE TITLE
Doesn't work with VLC 2.2.4

### ISSUE THREAD

**Issue by ghispi** [nurupo/vlc-pause-click-plugin#22]
I've downloaded release 0.3.1 (vlc-2.2.x-64bit-win.zip) and went as instructed.
Plugin is visible in video filters, enabled and button is selected yet clicking on video doesn't pause the video.

I'm on Win10 x64.
VLC 2.2.4 Weatherwax

**Comment by nurupo** [comment]
vlc-2.2.x-64bit-win.zip is a plugin for 64-bit version of VLC, it won't work with 32-bit VLC. Are you using 32-bit or 64-bit VLC?

**Comment by ghispi** [comment]
64-bit VLC most likely since it installed into "c:\Program Files\", not "c:\Program Files (x86)\".

**Comment by nurupo** [comment]
Also, another common mistake is forgetting to check both checkboxes: one in filters and another in interface (see instructions).

**Comment by ghispi** [comment]
Aaahhhhh, yep, sorry for confusion.
Those lines are to similar and my mind just skipped it reading it... and it did it twice!

**Comment by nurupo** [comment]
Cool, glad I could help.
