### ISSUE TITLE
Different $(libdir) path on Debian 9 "Stretch" amd64

### ISSUE THREAD

**Issue by Pleskan** [nurupo/vlc-pause-click-plugin#23]
You would use a different library path for plugin when using plugin with VLC on Debian 9.
The correct path is _/usr/lib/x86_64-linux-gnu/vlc/plugins_ , not just _/usr/lib/vlc/plugins_
Please pay attention on this and correct for the sake of the Great Perfection :-)

**Comment by nurupo** [comment]
Interesting. I use the plugin on Debian 8. Does that mean that Debian has changed where things are on the file system between its versions, or was I putting the file in the wrong directory from the start?

**Comment by Pleskan** [comment]
Neither the first nor the second, I guess _sudo dpkg --add-architecture i386_ may solve the issue.
I will test this and report here.

**Comment by Pleskan** [comment]
No, it was wrong suggestion. Summarizing all mentioned above: when using _amd64_ version of VLC, place plugin file at _/usr/lib/x86_64-linux-gnu/vlc/plugins_
You may reproduce the issue on virtual machine as well.

**Comment by nurupo** [comment]
Hm, looks like the paths have changed between Debian 8 and Debian 9.

E.g., the plugin binary from `vlc-plugin-notify` package in

- Debian 8 [is stored at `/usr/lib/vlc/plugins/notify/libnotify_plugin.so`](https://packages.debian.org/jessie/amd64/vlc-plugin-notify/filelist)
- Debian 9 [is stored at `/usr/lib/x86_64-linux-gnu/vlc/plugins/notify/libnotify_plugin.so`](https://packages.debian.org/stretch/amd64/vlc-plugin-notify/filelist)

I wonder what would be the best way to fix this. Is there some env. variable that specifies the right path on both of those systems?

**Comment by nurupo** [comment]
Looks like querying pkg-config about `vlc-plugin`'s libdir location should be the most portable solution.

**Comment by nurupo** [comment]
Thanks for pointing this issue out. Just released a new version fixing this issue.

**Comment by Pleskan** [comment]
OK, many thanks for fast feedback.
Cheers!
