### ISSUE TITLE
Linux Mint 17 (VLC 2.2.2)

### ISSUE THREAD

**Issue by Alex-Space** [nurupo/vlc-pause-click-plugin#24]
In menu after added to /home/master/.local/share/vlc/plugins/video_filter there is no chackbox in Interface settings window.
![selection_048](https://user-images.githubusercontent.com/7780469/28242126-815dc386-69c5-11e7-94ab-a1ca8a00dd2e.jpg)

**Comment by nurupo** [comment]
Sounds like the plugin was installed in incorrect location.

1. Are you sure `/home/master/.local/share/vlc/plugins/video_filter` is the correct location?
2. Did you run `sudo make install`?
3. What is the output of `pkg-config vlc-plugin --variable=pluginsdir`?

**Comment by nurupo** [comment]
While you are at it, make sure you have restarted VLC after installing the plugin and that you have built the plugin from `vlc-2.2.x+` directory.

**Comment by nurupo** [comment]
Closing for no reply in 7 days.
