### ISSUE TITLE
Usage improvement ?

### ISSUE THREAD

**Issue by dfleury2** [nurupo/vlc-pause-click-plugin#26]
Hi, I follow the usage without success.
I found that sometimes, the callback is followed by atmo, like    "pause_click:atmo"
I only succeed to make the plugin work, if I put atmo at to two places where pause_click is put.

Is this normal ?

**Comment by nurupo** [comment]
What "callback"? What are you talking about?

I have no idea what the atmo plugin is or what it does. This plugin works on its own, it doesn't require any additional plugins for it to work. It has been tested to work on clean installs of VLC 2.1 and 2.2, both 32 and 64 bit, on Windows and VLC 2.2 as provided by Debian Buster.

**Comment by dfleury2** [comment]
Yes, may be I miss a step. It works fine. Thanks
