### ISSUE TITLE
Instructions for Debian 

### ISSUE THREAD

**Issue by jolugaju** [nurupo/vlc-pause-click-plugin#28]
I think the instructions for the Debian versions aren't complete.
Just install 3 packages and then make and then install?
Maybe it's just my problem because I'm a newbie with Linux.

**Comment by nurupo** [comment]
The instructions are complete. I'm running Debian and those instructions is how I install the plugin. This plugin is not packaged in Debian (I have asked `vlc` package maintainer to package it but they said they have their hands full, which is understandable), so you have to build it from source, which is what the instructions walk you though.

**Comment by nurupo** [comment]
Since you are a newbie I probably should clarify that you are expected to run

```sh
make
sudo make install
```

commands while being inside the directory containing the files from this repository, so

```sh
sudo apt-get install build-essential pkg-config libvlccore-dev
sudo apt-get install git
git clone https://github.com/nurupo/vlc-pause-click-plugin.git
git checkout 0.4.0
make
sudo make install
```

**Comment by jolugaju** [comment]
Now I see. Those 7 lines clarify everything to me.
I was just used to double click an exe.
Thanks a lot. Much appreciated.

**Comment by jolugaju** [comment]
As soon as I try this I'll close the issue.

**Comment by nurupo** [comment]
So, how is it going?

**Comment by jolugaju** [comment]
It works perfect!
Thanks a lot!
