### ISSUE TITLE
Mouse click on music track

### ISSUE THREAD

**Issue by skorpionde** [nurupo/vlc-pause-click-plugin#29]
Hello,
your Plugin is very great for videos.

How does it works on music traks without video picture on the interface?
Or can you input this funktion also for musictracks?

Many Greetings

**Comment by nurupo** [comment]
The plugin works by reacting on mouse click events done on the video image (it implements the `video filter` plugin interface of VLC), so it's not possible to do the same for music tracks as there is no video image present.
