### ISSUE TITLE
Plugin not listed on Mac OS 10.11.6 and VLC 3.0.0, found a command line fix

### ISSUE THREAD

**Issue by datadog23** [nurupo/vlc-pause-click-plugin#32]
Hi, thanks for maintaining this handy plugin!

I had difficulty installing at Step 3, as the plugin wasn't listed in Settings -> Interface -> Control Interfaces. However, after running

`/Applications/VLC.app/Contents/MacOS/VLC --reset-plugins-cache`

it appeared and now works.

Thought you might want to add that to the Mac installation instructions; I can't work out how to get it to rebuild the plugin module list cache from within the GUI though.

**Comment by nurupo** [comment]
Hm, interesting. `--reset-plugins-cache` command line option is available on Windows and Linux too, but you don't have to use it to get the plugin listed. I will add it to the instructions though. Happy to learn the macOS binary is actually working, I have a macOS machine to build nor test it, it was built on Travis-CI.

**Comment by nurupo** [comment]
Alright, added it in https://github.com/nurupo/vlc-pause-click-plugin/commit/de367296135a71f350c03cb869b6e8335250ec35, to the troubleshooting section though, since it's not common to have to reset plugin cache for the plugin to work. In fact, you are probably the first or second (someone had to delete their VLC settings directory on Ubuntu to get the plugin to appear) person to have reported that.

**Comment by nurupo** [comment]
Thanks!

**Comment by cynoclast** [comment]
I tried `--reset-plugins-cache` on Win10x64 with VLC 3.0.12x64 and Plugin 3.0.x64 and it still doesn't appear.

**Comment by chrisgrieser** [comment]
Can also report, neither `--reset-plugins-cache` nor VLC reinstall helped – the plugin simply doe snot show up in the settings.

---

macOS 12.2.1
Version 3.0.17.3 Vetinari (Apple Silicon)

**Comment by SwineBurglar** [comment]
This plug-in is also not working for me on MacOS 12.6.1 using VLC 3.0.17.3 (Apple Silicon). I get the feeling there is something different about how plug-ins work in the Apple Silicon version of VLC, and this plug-in needs to be updated for it. I just installed this plug-in on my main Mac and another server which both use Intel processors and the plug-in works with no problems. My third computer is an Apple Silicon Mac Mini and this plug-in will not show up in the plug-ins list in VLC.

**Comment by TLFulton** [comment]
Does not work for me: Windows 11X64, VLC 3.0.18

**Comment by nurupo** [comment]
@SwineBurglar the current macOS binaries are build for Intel CPUs only. Support for Apple silicon was added just a few days ago and the upcoming release will include Apple silicon supporting binaries. Meanwhile [these testing binaries should work on Apple Silicon](https://github.com/nurupo/vlc-pause-click-plugin/pull/93#issuecomment-1351132206), so give them a try.

**Comment by SwineBurglar** [comment]
@nurupo Hey! Thank you so much for letting me know. I really appreciate that. This will be the final bit of icing on my M1 Mac Mini home theater computer cake. :) I am pumped. My controller set up will benefit greatly from being able to click to pause.

**Comment by Beer5-0** [comment]
Win11  VLC 3  (3.0.20 Verinari)  
:) me made folder with the plugin name ( libpause_click_plugin ) in VLC plugins folder and pasted the dll inside
(+ install-clicking-around-in-vlc-guide ) and it worked   :) 
C:\Program Files\VideoLAN\VLC\plugins\libpause_click_plugin\libpause_click_plugin.dll   

sigle click - play/pause       double click - fullscreen on/off       

cheers, be good, Pay It Forward and have a nice day, night, week, month, year. life!

**Comment by TroglodyteGuy** [comment]
Not working for me with latest VLC version (32-bit): **3.0.20-win32**.

I have tried:
+ Uninstall/install -- both selecting to delete preferences and cache
+ Run exe with the flag mentioned by others (**--reset-plugins-cache**)
+ Create a subfolder in the (libpause_click_plugin) as a child of the "**video_filter**" folder and copy in the dll (**libpause_click_plugin.dll**) -- note: tried with the plugin also in the video_filder folder at the same time (2 places) and with it only in the new subfolder. Neither option helped.

None of the above helped, and would like to find a solution.

Any other suggestions for things I may have missed?

**Comment by Zaid1jo** [comment]
it works when extract the file in "C:\Program Files\VideoLAN\VLC\plugins                              (for 64-bit VLC)
                                                    "C:\Program Files (x86)\VideoLAN\VLC\plugins                    (for 32-bit VLC)"

**Comment by Wolfsaf** [comment]
Can also report, neither --reset-plugins-cache nor VLC reinstall helped – the plugin simply doe snot show up in the settings.
Does not work for me: Windows 11 x64, VLC 3.0.21 x64.

**Comment by gtarroni** [comment]
**Plugin does not show up** (despite trying the `/Applications/VLC.app/Contents/MacOS/VLC --reset-plugins-cache` command), sadly. Using Version 3.0.23 Vetinari, and having downloaded the VLC 3.0 version.

**Comment by nileshparmar1979** [comment]
Works within the settings on latest mac version [3.0.23] but the fix doesnt play and pause upon click on the screen/video.

<img width="500" height="auto" alt="Image" src="https://github.com/user-attachments/assets/1ca3f747-2b6b-49c8-a957-6ccea45182c6" />
