### ISSUE TITLE
Can't install on snap

### ISSUE THREAD

**Issue by giuseppe-dandrea** [nurupo/vlc-pause-click-plugin#33]
Is there a way to install the plugin if I installed vlc 3 through snap? I'm using a debian-based distro of linux but the debian instruction doesn't work, maybe because snap installs the applications in a read-only partition in the root directory.  Tried to copy the .so file in /snap/vlc/usr/lib etc.. but can't write in the directory. Is there another way to install the plugin or to copy the file in that directory? (Tried to change the permissions but without success)

**Comment by nurupo** [comment]
Sorry, don't know anything about snaps. Also, the build instructions build the plugin for your system's VLC, if the version of the VLC from your package repository differs from the one in the snap, e.g. VLC 2.2 vs VLC 3.0, then the plugin won't work. You can't use a plugin built for VLC 2.2 in VLC 3.0 (same with any other combination of 2.1, 2.2 and 3.0).

**Comment by nurupo** [comment]
It sounds like snaps can't be modified, so you can't add the plugin file in there. The next best thing would be to copy over all the VLC plugins from the snap somewhere into your home directory and then run vlc with `VLC_PLUGIN_PATH` env variable set pointing to where you copied all the plugins, including the vlc-pause-click-plugin. But then you'd need to copy over the plugins every time you update the VLC snap, as well as to figure out how to build the plugin against the VLC snap, which might not be possible if the snap doesn't provide SDK.

Can you run the `tree` command inside the root directory of VLC snap and paste-bin somewhere the output? Want to see if it includes the SDK. If it doesn't include it, then there is no way you are building the plugin for that VLC.

**Comment by giuseppe-dandrea** [comment]
Here is the output https://github.com/giuseppe-dandrea/tree-snap-vlc-output/blob/master/output.txt
Was too big for pastebin

**Comment by nurupo** [comment]
Alright, it does include the SDK, so it's possible to build the plugin against it, it just won't be pretty. Can you tell where is the snap located at? I see`current/usr/lib/libvlccore.so` file exists, but I need an absolute path to it, starting with root directory. With that information I could try writing a bash script for building the plugin for you.

**Comment by giuseppe-dandrea** [comment]
The path of the snap directory is simply /snap, in the root, in this folder there is the list of all snap applications, so the full path is /snap/vlc and you can see from the output that in this folder there are the folders for the versions (just the 158 in that case) and the symlink to the current version (current). Thanks a lot for the help

**Comment by giuseppe-dandrea** [comment]
Tried to ask in the snap forum too for more info, but seems that there isn't a way without recompiling the snap... https://forum.snapcraft.io/t/call-for-testing-vlc-3-0-0-rc1/3202/44

**Comment by nurupo** [comment]
Right, it's a security feature.

Anyway, I'm convinced that we can make it work.

Try this to build the plugin binary against the VLC SDK from the snap:

```bash
sudo apt-get install build-essential pkg-config git
cd ~
git clone https://github.com/nurupo/vlc-pause-click-plugin
cd vlc-pause-click-plugin
git checkout 1.0.0 
cp -a /snap/vlc/current/usr/lib/pkgconfig .
sed -i "s|^prefix=.*|prefix=/snap/vlc/current/usr|g" pkgconfig/*.pc
export PKG_CONFIG_PATH="${PWD}/pkgconfig"
make
```

Now place the plugin whenever you want on your system, for this example I will just use `~/.config/vlc/plugins`:

```bash
mkdir -p ~/.config/vlc/plugins
cp libpause_click_plugin.so ~/.config/vlc/plugins
```

Now start VLC, telling it to check `~/.config/vlc/plugins` for extra plugins. You'd do usually do it like this:

```bash
VLC_PLUGIN_PATH=/home/giuseppe-dandrea/.config/vlc/plugins /snap/vlc/current/bin/vlc
```

changing the username in the path yours, but there is a little complication here, as it seems that you don't start the snap VLC by directly running `/snap/vlc/current/bin/vlc` but rather `/snap/vlc/current/bin/vlc-snap-wrapper.sh` or something else, which might override `VLC_PLUGIN_PATH`, throwing away whatever we have set it to . Could tell what exactly do you run to start the snap VLC? If it's a desktop icon, open it in a text editor and see what program it calls. I think it calls `vlc-snap-wrapper.sh`, but I don't have snap installed to be check if it is so. If it's so, pastebin the contents of `vlc-snap-wrapper.sh` somewhere.

**Comment by giuseppe-dandrea** [comment]
All the commands worked but the last, wich said that /snap/vlc/current/bin/vlc doesn't exist. In fact in that folder there are only two files, but if I try to run them these are the output:
```./desktop-launch
Can't save user-dirs.dirs
mkdir: cannot create directory '/.config/dconf': Permission denied
ln: failed to create symbolic link '/.config/dconf': Permission denied
./desktop-launch: riga 335: /flavor-select: File o directory non esistente
 ``` 
``` ./vlc-snap-wrapper.sh
Unsupported architecture for this app build
```
https://github.com/giuseppe-dandrea/tree-snap-vlc-output here i pushed the content of the folder.

I usually start vlc by typing vlc in the terminal or I have a script that exec vlc with the media argument, anyway don't have a desktop icon or start it by double-click on the media.

**Comment by nurupo** [comment]
>I usually start vlc by typing vlc in the terminal 

Does typing `vlc` in the terminal start the snap VLC or the VLC packaged by your distribution?

**Comment by giuseppe-dandrea** [comment]
@nurupo the snap vlc, wich is the only version installed

**Comment by nurupo** [comment]
Oh, then just do

```bash
VLC_PLUGIN_PATH=/home/giuseppe-dandrea/.config/vlc/plugins vlc
```

then, assuming you have the `libpause_click_plugin.so` plugin binary in `/home/giuseppe-dandrea/.config/vlc/plugins`. If everything works, you should see the plugin options appear in the preferences ([here are screenshots](https://github.com/nurupo/vlc-pause-click-plugin#usage)).

**Comment by giuseppe-dandrea** [comment]
No it doesn't work, the command starts vlc but in the preferences there aren't new checkboxes, tried with `--reset-plugins-cache` too but no luck

**Comment by nurupo** [comment]
Try it a bit differently then

```bash
export VLC_PLUGIN_PATH=/home/giuseppe-dandrea/.config/vlc/plugins
vlc
```

**Comment by nurupo** [comment]
If that doesn't work there are a few possibilities here

1. VLC can't access the `VLC_PLUGIN_PATH` for some reason
  - Incorrect `VLC_PLUGIN_PATH` was specified
  - File permission issue
  - Snap apps are sandboxed?
2. Snap VLC was made to ignore `VLC_PLUGIN_PATH` by whoever made the snap
3. Plugin is not compatible with the snap VLC (e.g. it was build against system libvlccore instead)

You could look into 1 on your own, check that the path, file permissions, etc. are correct there.

I have no idea how to check 2.

For 3, repeat the build process from scratch and pastebin output of the `make` and `ldd` commands

```bash
sudo apt-get install build-essential pkg-config git
cd ~
git clone https://github.com/nurupo/vlc-pause-click-plugin
cd vlc-pause-click-plugin
git checkout 1.0.0 
cp -a /snap/vlc/current/usr/lib/pkgconfig .
sed -i "s|^prefix=.*|prefix=/snap/vlc/current/usr|g" pkgconfig/*.pc
export PKG_CONFIG_PATH="${PWD}/pkgconfig"
make
sudo apt-get install build-essential pkg-config git
cd ~
git clone https://github.com/nurupo/vlc-pause-click-plugin
cd vlc-pause-click-plugin
git checkout 1.0.0 
cp -a /snap/vlc/current/usr/lib/pkgconfig .
sed -i "s|^prefix=.*|prefix=/snap/vlc/current/usr|g" pkgconfig/*.pc
export PKG_CONFIG_PATH="${PWD}/pkgconfig"
make
ldd libpause_click_plugin.so
```

**Comment by giuseppe-dandrea** [comment]
Ok then,
1- Double checked the path and set all the permissions in the plugin folder to 777.
2- Don't know that
3- Here is the output:
```
make output:
cc -std=gnu11 -g0 -O3 -Wall -Wextra -fPIC -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/snap/vlc/current/usr/include -I/snap/vlc/current/usr/include/vlc/plugins -DPIC -I. -Isrc -DMODULE_STRING=\"pause_click\"  -c -o pause_click.o pause_click.c
cc -std=gnu11 -shared -o libpause_click_plugin.so pause_click.o  -L/snap/vlc/current/usr/lib -lvlccore
```
```
ldd output:
	linux-vdso.so.1 (0x00007ffd863ad000)
	libvlccore.so.9 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fae5e065000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fae5e607000)
```

**Comment by nurupo** [comment]
`make` and `ldd` outputs look good.

Can you run:

```bash
VLC_PLUGIN_PATH=/home/giuseppe-dandrea/.config/vlc/plugins vlc --verbose 2
```

(replace `/home/giuseppe-dandrea/.config/vlc/plugins` with the path to whatever directory you put the plugin `.so` file into)

then close VLC and and pastebin the output?

**Comment by giuseppe-dandrea** [comment]
Ok this helped, it show that vlc is exploring the folder with the plugin (ps. tried to copy the plugin also in a folder called video_filters in the plugin folder), but tried with or without the plugin file and it loads 508 modules.
Here is the output: https://github.com/giuseppe-dandrea/tree-snap-vlc-output/blob/master/vlc_output

**Comment by nurupo** [comment]
So, since the number of plugins doesn't change, then VLC simply doesn't/can't load it. Can you provide output of `ldd` on one of the plugins VLC comes with? 

Something like

```bash
ldd /snap/vlc/current/usr/lib/vlc/plugins/video_filter/libpuzzle_plugin.so
```

Not sure if that's the correct path to the plugin though, fix it if it's not.

**Comment by nurupo** [comment]
Actually, do `ldd -v` both on `libpause_click_plugin.so` and then on `/snap/vlc/current/usr/lib/vlc/plugins/video_filter/libpuzzle_plugin.so`.

Also, what is your distribution release version?

My current guess is that VLC is not loading the plugin due to libc incompatibilities or due to some missing shared library dependencies (i.e. the `dlopen()` call on `libpause_click_plugin.so` within VLC fails).

**Comment by giuseppe-dandrea** [comment]
> Also, what is your distribution release version?

I'm using Deepin 15.5 based on Debian with i3wm

Here is the output
```
ldd -v libpuzzle_plugin.so
linux-vdso.so.1 (0x00007ffc9bf75000)
	libvlccore.so.9 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f864175b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8641d0f000)

	Version information:
	/snap/vlc/current/usr/lib/vlc/plugins/video_filter/libpuzzle_plugin.so:
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```
```
ldd -v libpause_click_plugin.so
linux-vdso.so.1 (0x00007ffc61703000)
	libvlccore.so.9 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9a2eb2f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9a2f0d1000)

	Version information:
	/home/giuseppe/Desktop/Temp_Downloads/vlc-pause-click-plugin/libpause_click_plugin.so:
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

**Comment by nurupo** [comment]
Alright, [it appears](https://jenkins.videolan.org/job/vlc-nightly/job/vlc-3.0-nightly-snap/76/consoleFull) like the snap VLC is built on Ubuntu Xenial using gcc 5.4.0. We build the plugin using you system's gcc and linking it against your system's libc version, which are newer than the ones in Ubuntu Xenial. Meaning the the plugin might not be binary compatible with what VLC expects when it loads a plugin. This is just an educated guess though, I'm not 100% sure. The plugin is more likely to work if we build it on Ubuntu Xenial.

How willing are you to install Docker on your system so that we could try building the plugin using the Ubuntu Xenial container to see if it makes VLC load the plugin? I can guide you through the entire thing, it's actually easy, pretty much the build instructions you have used to build the plugin plus a couple of docker commands.

**Comment by giuseppe-dandrea** [comment]
Ok no problem, but never used Docker before, let me know how to do.

**Comment by nurupo** [comment]
Well, first install it. Not sure if your distribution packages it, but I'm using Debian and it doesn't, so I have to add Docker's package repository to get it https://docs.docker.com/install/linux/docker-ce/debian/. Deepin 15.5 looks to be based on Debian Stretch, so installing Docker sums up to

```bash
sudo apt-get install \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo echo "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable" >> /etc/apt/sources.list
sudo apt-get update
sudo apt-get install docker-ce
```

To build the plugin in a Ubuntu Xenial container do

```bash
mkdir result
# This will create a temporary ubuntu 16.04 container with your system's $PWD/result
# being mounted in container's /result and your system's /snap in container's /snap
# and will start bash inside of the container
sudo docker run --rm -it -v $PWD/result:/result -v /snap:/snap ubuntu:16.04 /bin/bash
# Now you are in a bash session inside the container, which you can see by the changed
# command prompt, which would be something like root@11212a8998fc, so whatever
# you do here won't affect your system
apt-get update
# Now we follow the instructions on building the plugin
apt-get install build-essential pkg-config git
# Make sure the GCC version is 5.4.0
gcc --version
cd /result
git clone https://github.com/nurupo/vlc-pause-click-plugin
cd vlc-pause-click-plugin
git checkout 1.0.0 
cp -a /snap/vlc/current/usr/lib/pkgconfig .
sed -i "s|^prefix=.*|prefix=/snap/vlc/current/usr|g" pkgconfig/*.pc
export PKG_CONFIG_PATH="${PWD}/pkgconfig"
make
# Now that we have built the plugin, let's exit the container, which will also destroy it
logout
# Free disk space by deleting the downloaded Ubuntu 16.04 base image
sudo docker rmi ubuntu:16.04
# You should have the plugin in result/vlc-pause-click-plugin directory
# Change the ownership to your user, as it is owned by root because we
# were running as root inside the container
sudo chown giuseppe:giuseppe -R result
```

Now try making VLC use the plugin you got in `result/vlc-pause-click-plugin`, e.g. put it in `/home/giuseppe/.config/vlc/plugins/` and try the `VLC_PLUGIN_PATH=/home/giuseppe/.config/vlc/plugins vlc`, it might work now that the plugin is built using the same versions of the compiler and libc.

**Comment by giuseppe-dandrea** [comment]
Followed all the steps, no error message, gcc version 5.4.0... Only 508 plugins and no new checkboxes in the preferences.. I think that there's no way to install new plugins in snap vlc without recompile it. Thanks a lot for the help, if you have new ideas I'm happy to try, otherwise I could close the issue.

**Comment by nurupo** [comment]
Do you keep the plugin name the same, i.e. `libpause_click_plugin.so`? I'm going though VLC source code for loading plugins and it searches specifically for `lib*_plugin.so` pattern when loading a module, so renaming it to anything else would prevent VLC from loading it https://github.com/videolan/vlc/blob/3.0.0-git/src/modules/bank.c#L367

**Comment by giuseppe-dandrea** [comment]
Yes the name is the same
```
giuseppe@giuseppe-PC:~$ ls .config/vlc/plugins/
libpause_click_plugin.so
```

**Comment by nurupo** [comment]
What does

```bash
LD_BIND_NOW=1 VLC_PLUGIN_PATH=/home/giuseppe/.config/vlc/plugins vlc --verbose 2
```

output?

**Comment by giuseppe-dandrea** [comment]
Here is the output
https://github.com/giuseppe-dandrea/tree-snap-vlc-output/blob/master/vlc_output2

**Comment by giuseppe-dandrea** [comment]
Ok, thanks again for the help.
