### ISSUE TITLE
Not working on VLC 3.0.1 Windows 10

### ISSUE THREAD

**Issue by Notare** [nurupo/vlc-pause-click-plugin#35]
Plugin doesn't even appear in preferences

**Comment by nurupo** [comment]
Make sure that the bitness of the plugin matches that of VLC, e.g. if you use 32-bit VLC, you must use 32-bit plugin. Also make sure you use the plugin for VLC 3.0 and not some other VLC version, though I probably don't have to mention this.

**Comment by nurupo** [comment]
Pretty mcuh this https://github.com/nurupo/vlc-pause-click-plugin#i-dont-see-any-plugin-related-options-described-in-usage-instructions-in-my-vlc-preferences.

**Comment by Notare** [comment]
Sorry for the stupidity, the older version of VLC I had was 32bit but when I installed the newer version (3.0 64bit), the 32bit folder continued in Program Files and I was installing the plugin there, I didn't pay attention to this, now I installed in the 64bit folder and is all working.
