### ISSUE TITLE
Plugin doesn't show up, Mac OS High Sierra, VLC 3.1 64bit

### ISSUE THREAD

**Issue by alexqndr** [nurupo/vlc-pause-click-plugin#36]
Hello,

I tried to install the plugin but it doesn't show up in the advanced interface settings. I tried all the troubleshooting bullet points, apart the cache clean one because I am a code/terminal noob. 

Any help would be appreciated. Thanks for your work

**Comment by alexqndr** [comment]
My bad! I wasn't placing the extension file in the appropriate folder.

**Comment by plasmidone** [comment]
Hello, which folder is it supposed to be in for macOS?

I used the /Applications/VLC.app/Contents/MacOS/plugins but the plugin does not show up, even after restarting, purging VLC's cache etc.
