### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by bantya** [nurupo/vlc-pause-click-plugin#37]
I really want to thank you for this awesome plugin. I couldn't find your social media channels thus posting it here. Many many thanks again.

**Comment by nurupo** [comment]
You are welcome.

**Comment by nurupo** [comment]
Feel free to star the repository ;)

**Comment by DimaDK24** [comment]
I just want to join the thanks. Your plugin works nice and so easy to use. I can't imagine using VLC without the feature brought by you. Thank you for that
