### ISSUE TITLE
Settings options show but click-pause doesn't work

### ISSUE THREAD

**Issue by Yakumounr** [nurupo/vlc-pause-click-plugin#38]
I've set Interface -> Control Interfaces -> Pause/Play video 
I've checked the settings under Video - Filters.
I've tested different button/wheel settings, and toggled the double click detection.

Clicking the video just doesn't do anything.

**Comment by nurupo** [comment]
Do you still need help with this?

**Comment by Yakumounr** [comment]
I thought I'd just missed the control interfaces setting, so closed this and changed to delete.
Then re-opened it when I found it still didn't actually work for me, I thought I'd reset the title as well before rushing out and forgetting about it all, sorry.

**Comment by Yakumounr** [comment]
VLC 3.01 x64, Win 10 pro x64

**Comment by Yakumounr** [comment]
With both of those ticked it worked after a couple of restarts.

**Comment by nurupo** [comment]
Huh. Well, glad that it worked for you :)
