### ISSUE TITLE
Works for win 7 64bit

### ISSUE THREAD

**Issue by pbpb** [nurupo/vlc-pause-click-plugin#4]
64 bit dll works for me for vlc 2.2.0 on win 7 sp1.  ...So far, anyway, after an hour.

**Comment by nurupo** [comment]
What this issue is about? If you don't have any issues, then don't create an issue. I'm closing this.

**Comment by nurupo** [comment]
I only now realized that this was about the Windows dll that is marked as "Not tested". Thanks for reporting then, and sorry for the first reply : )
