### ISSUE TITLE
Broken after VLC update to 3.0.3 ?

### ISSUE THREAD

**Issue by Xtian60** [nurupo/vlc-pause-click-plugin#40]
After reinstalling your .dll and appropriate settings, I still can't recover the functionality of this vital plugin in VLC 3.0.3 64bit.

**Comment by Xtian60** [comment]
Well, my bad.  After reinstall, including overwriting preferences, it seems to be working again.  Too bad that I had to lose all my preferences, but seems more like a VLC issue.  Next time, I'll try disabling the plugin prior to update.

**Comment by USteppin** [comment]
How'd you fix it? A full reinstall of VLC?

**Comment by nurupo** [comment]
You could try using [the troubleshooting guide](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting), specifically this point:

>- Some users have reported that they had to run the VLC executable with `--reset-plugins-cache` flag once for the plugin to appear in the GUI.

Not sure if it will help you, but sounds like it might. Just keep in mind that this might reset all VLC settings to default, given how everything in VLC is a plugin, even GUI.
