### ISSUE TITLE
using the plugin with c# vlclib

### ISSUE THREAD

**Issue by Arashz22** [nurupo/vlc-pause-click-plugin#42]
Hello dear developer
I had added your plugin to my VLC player sucessfully.
but I am making my own player using [Vlc.DotNet](https://github.com/ZeBobo5/Vlc.DotNet)
I've copied your dll file in the folder which you said and I'm seeking for something like this: 
```
myVlcControl.VlcMediaplayerOptions = new string[] {
                "--enable-pause_click",
            };
```
is it a way to use this plugin for my own c# solution ?

**Comment by nurupo** [comment]
Sorry, I can't help you with that, I don't know anything about Vlc.DotNet.
