### ISSUE TITLE
can't use this on Windows 7 without the flag

### ISSUE THREAD

**Issue by DDoyle022** [nurupo/vlc-pause-click-plugin#48]
I'm running Windows 7 Enterprise sp1.  this plugin worked for quite a while but stopped working around 6 months ago.   When I tried to find the play/pause settings, they weren't there.

I found the problem referenced in troubleshooting, where you add the `--reset-plugins-cache` flag.  When I run it via command line with that flag, the play/pause settings are there and the plugin works.  But if I close and restart VLC normally, the settings are gone and it no longer works.

I'm running 3.0.3 Vetinari 32-bit version.

**Comment by nurupo** [comment]
Is it possible that you have two different versions of VLC installed? The version that you start from the command line with the `--reset-plugins-cache` flag has the plugin installed, but the version that you normally start, e.g. use a desktop shortcut, if actually an entirely different version of VLC that doesn't have the plugin? This happened to someone before (they had both 32-bit and 64-bit VLC installed).

If you are sure that you have just a single version of VLC, I'd suggest to

1. Uninstall it
2. Make sure that all files from whenever it was installed into (the 32-bit version is probably installed into `C:\Program Files (x86)\VideoLAN\`) are gone, including the plugin
3. [Wipe all of its leftover data in `%APPDATA%/vlc`](https://wiki.videolan.org/VSG:ResetPrefs/#Deleting_the_files_manually)
4. Install it back
5. Add the plugin file back and enable it with checkboxes

**Comment by DDoyle022** [comment]
Wow, I can't believe I missed that.  Yes, that was the issue.  The plugin now works for me.  Thanks.

**Comment by nurupo** [comment]
Glad I could help.
