### ISSUE TITLE
The usage instructions explains only Windows version

### ISSUE THREAD

**Issue by itsthomas** [nurupo/vlc-pause-click-plugin#49]
Hi,
The usage instructions explains only how to activate the plugin for Windows version of VLC player.
Here, I put the instruction for the Mac version of VLC 3:

**Go to VLC -> Preferences**

![screenshot 2018-11-20 at 16 07 59](https://user-images.githubusercontent.com/4038628/48786500-e7c2d380-ecde-11e8-861e-c5ee07e8de9e.png)

**Now click on "Show All" button in the bottom left side of the window:**

![screenshot 2018-11-20 at 16 08 13](https://user-images.githubusercontent.com/4038628/48786512-ef827800-ecde-11e8-9786-1ba466421730.png)

**Activate the plugin once here:**

![screenshot 2018-11-20 at 16 08 28](https://user-images.githubusercontent.com/4038628/48786541-fc9f6700-ecde-11e8-9bfa-254ed9a334c9.png)

**And activate it also here:**

![screenshot 2018-11-20 at 16 08 47](https://user-images.githubusercontent.com/4038628/48786554-045f0b80-ecdf-11e8-932d-92449a406b29.png)

**Restart VLC player and the plugin should work.**

**Comment by nurupo** [comment]
>The usage instructions explains only how to activate the plugin for Windows version of VLC player.

Although the screenshots are of the Windows VLC, they work for both Windows and Linux as VLC uses the same Qt-based interface on those platforms, it's identical, so the instructions are not Windows-only.

I don't own a Mac system, so I can't take any macOS screenshots and I'm rather clueless as to what VLC uses for the user interface on macOS (I think I heard sometime ago that it uses naive macOS interface over the Qt based one on macOS? not sure), but from the screenshots I have seen on the web, the interface looks closely enough to that of what VLC uses on Windows and Linux, so the Windows instructions and screenshots, while not 100% precise, should fine for macOS.

I can make separate instructions for MacOS, with the text corrected for macOS VLC, with macOS screenshots, if you are willing to provide all 7 of the screenshots from the [Usage section](https://github.com/nurupo/vlc-pause-click-plugin#usage).

**Comment by nurupo** [comment]
Forgot to mention, if you provide the 7 screenshots, don't circle things in red in them, provide just plain screenshots without any editing.

**Comment by nurupo** [comment]
Well, can't make macOS instructions without all of the screenshots and you are not providing them, so there is nothing I can do here. Closing the issue.

**Comment by caltlgin** [comment]
@nurupo please see @itsthomas original issue which he updated with screenshots and instructions. https://github.com/nurupo/vlc-pause-click-plugin/issues/49#issue-382732622
