### ISSUE TITLE
Can't get it to work on Ubuntu 18.04

### ISSUE THREAD

**Issue by shukero** [nurupo/vlc-pause-click-plugin#50]
HI everyone,

For some reason I can't get this to work on Ubuntu 18.04 :(. I tried to follow the normal install guide for debian Linux install:

`sudo apt-get install build-essential pkg-config libvlccore-dev libvlc-dev`
But when I tried to do the: 
`make
sudo make install`

It gave me this:
`make: *** No targets specified and no makefile found.  Stop.`

So I looked at others having this issue; and I found the following for an older version of VLC:

'Sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo reboot
sudo apt-get install vlc git
git clone https://github.com/nurupo/vlc-pause-click-plugin.git
cd vlc-pause-click-plugin/vlc-2.2.x+
sudo apt-get install build-essential pkg-config libvlccore-dev
make
sudo make install`

I got to: `cd vlc-pause-click-plugin/vlc-2.2.x+` before running into an issue - as there is no directory like this now.

Could someone please help me finish this install so I can get click to pause on VLC 3.0.3?

Thanks,
~Mike

**Comment by nurupo** [comment]
Here are the dumbed down instructions:

```
sudo apt-get update
sudo apt-get install build-essential pkg-config libvlccore-dev libvlc-dev git vlc
git clone https://github.com/nurupo/vlc-pause-click-plugin
cd vlc-pause-click-plugin
git checkout 1.0.0
make
sudo make install
```

You can delete the "vlc-pause-click-plugin" directory after that.

**Comment by shukero** [comment]
HI Nurupo,

Thank you very much for the information :) - That worked.

HAve a great day,

**Comment by nurupo** [comment]
Cool, glad it worked. Feel free to open an issue if you have any trouble getting the plugin to work.
