### ISSUE TITLE
Doesn't work and showup in VLC 3.0.5 Snap version

### ISSUE THREAD

**Issue by SeriousHoax** [nurupo/vlc-pause-click-plugin#52]
I installed it with VLC 3.0.5 installed from Ubuntu Software on my Ubuntu 18.10. But it doesn't work. It's not showing up anywhere in VLC Preferences. Maybe a change was made in VLC 3.0.5. Can you look into it?

**Comment by nurupo** [comment]
3.0.5 is not the issue, the issue is you using the Snap version, it doesn't allow loading additional plugins, or at least so it seems https://github.com/nurupo/vlc-pause-click-plugin/issues/33.

**Comment by SeriousHoax** [comment]
Oh I see. Ok thanks. You may close the issue now.

**Comment by nurupo** [comment]
Yeah, we bashed our heads trying to make Snap VLC load the plugin but it just wouldn't see it. Your best bet is recompiling the entire Snap VLC yourself with the plugin included.

**Comment by shaunstone** [comment]
i know this is old but thought i would share,  to install plugins when vlc is installed via snap you need to put them in this directory
```./snap/vlc/current/.local/share/vlc/lua/extensions/```

at least this is what works on ubuntu 20.

**Comment by nurupo** [comment]
@shaunstone That's for lua plugins only. It will not work for this plugin as it's not a lua extension.
