### ISSUE TITLE
How to disable toggle fullscreen with mouse double click?

### ISSUE THREAD

**Issue by Bill-Jobss** [nurupo/vlc-pause-click-plugin#54]
I just have a question and I do not know where else to ask it. The plugin works great, thank you for creating it.

There is just a little annoyance that when I make two clicks close to each other, the player toggles fullscreen. A desired behavior for me would be that I toggle pause/play with left mouse clicks and double clicks, and the fullscreen toggle with mouse clicks would be either completely disabled, or reassigned to the middle mouse button.

I searched high and low, could not find anything. Is there any way to do that?

**Comment by nurupo** [comment]
The plugin has no control over the full screen on double click feature, it can't disable or reassign it. Ideally the plugin that provides it (the Qt interface) would give you an option to enable/disable that feature, but there doesn't seem to be such an option as far as I can see. So your best bet would be to modify VLC's source code to remove that feature (or add an option to disable it) and compile VLC off your modified source code. I can't really help you with that.

**Comment by Bill-Jobss** [comment]
Ok. Thank you anyway. Maybe they will include such an option in a future release.

**Comment by nurupo** [comment]
I very doubt it, I have googled forum posts about people asking for a way to disable double-click-to-full-screen from as early as 2008 (or was it 2006?). The devs either don't care for it and/or forgotten about it. Don't this the situation will change unless you open a feature request ticket in their bug tracker or implement it yourself and send VLC a patch, and then it's not guaranteed.

**Comment by Bill-Jobss** [comment]
Unfortunately, I have no experience with either C++ or QT, and I heard that VLC compilation is very troublesome. But I will try to open a feature request. Maybe someone will implement it. I am surprised that programming an interface causes so much trouble in C++. In VB.NET it is just a 10-minute job max.

**Comment by nurupo** [comment]
I just realized that the fullscreen toggle can be disabled by simply filtering out the double-click event. It can also be re-assigned to the middle button by telling VLC that middle button double-clicked.

I have pushed code changes to [`suppress-fullscreen`](https://github.com/nurupo/vlc-pause-click-plugin/tree/suppress-fullscreen) and here are Windows binaries:

- [vlc-2.1-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048508/vlc-2.1-32bit-win.zip)
- [vlc-2.1-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048509/vlc-2.1-64bit-win.zip)
- [vlc-2.2-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048510/vlc-2.2-32bit-win.zip)
- [vlc-2.2-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048511/vlc-2.2-64bit-win.zip)
- [vlc-3.0-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048512/vlc-3.0-32bit-win.zip)
- [vlc-3.0-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048513/vlc-3.0-64bit-win.zip)

Say if this works for you and what OS and VLC version you use.

I will likely include the fullscreen suppression as a checkbox option in the next release.

**Comment by nurupo** [comment]
Should be addressed by the 2.0.0 release https://github.com/nurupo/vlc-pause-click-plugin/releases/tag/2.0.0

**Comment by Bill-Jobss** [comment]
I know it's been a long time, but I just want to thank you so much for implementing this feature. If there exists a Karma, you've earned a great deal of it. (So technically, in the next life you will be reborn like, I don't know, a Batman. Or something to that effect.) Wish you good health also.
