### ISSUE TITLE
Does not work on Kubuntu 18.04

### ISSUE THREAD

**Issue by zlobolet** [nurupo/vlc-pause-click-plugin#57]
KDE Plasma 5.12.7
Qf 5.9.5
64 bit

VLC 3.0.4 Vetinari

**Comment by nurupo** [comment]
Do the plugin-related settings show up in VLC?

**Comment by zlobolet** [comment]
<img src="https://i.imgur.com/Z58cF0p.png" />
Russian version

**Comment by nurupo** [comment]
Make sure that both of those are checked

![](http://i.imgur.com/aMkGRRK.png)

and

![](http://i.imgur.com/U5TZpDp.png)

**Comment by zlobolet** [comment]
Sorry, it worked

**Comment by nurupo** [comment]
Cool, glad you got it working!
