### ISSUE TITLE
Doesn't display in filters list

### ISSUE THREAD

**Issue by dkomer** [nurupo/vlc-pause-click-plugin#6]
I compiled on an Ubuntu Virtual machine- and I can see the filter listed in vlc --list

But when I go into the GUI video filters (show all, etc.) - I do not see it there. Any tips?

Also, any hints on cross-compiling to get a windows dll are much appreciated! I've been going crazy trying to figure that out, hehe. Thanks!

**Comment by dkomer** [comment]
nevermind- it displays there just fine ;)

**Comment by nurupo** [comment]
>Also, any hints on cross-compiling to get a windows dll are much appreciated! I've been going crazy trying to figure that out, hehe. Thanks!

There are dll download links provided in README.md.

If for some reason you want to build them yourself, what I did was getting VLC source code, integrating my plugin in it and then cross-compiling the entire VLC for Windows. I don't have precise instructions, but there are some articles on how to cross-compile VLC which might help. Also, to integrate the plugin into VLC source tree you just have to copy `pause_click.c` into `modules/video_filter/` and add

```
libpause_click_plugin_la_SOURCES = pause_click.c
libpause_click_plugin_la_CFLAGS = $(AM_CFLAGS)
libpause_click_plugin_la_LIBADD = $(AM_LIBADD)
video_filter_LTLIBRARIES += libpause_click_plugin.la
```

to the  `Modules.am` that is in the same directory.
