### ISSUE TITLE
Adding support for audio only possible?

### ISSUE THREAD

**Issue by fennelpollen** [nurupo/vlc-pause-click-plugin#60]
Just wondering if it might be possible to add support for audio only? Meaning there is no video, just a black window (perhaps with the cone graphic in the middle). I'd still like to click the screen to pause, even it's audio only.

**Comment by nurupo** [comment]
I believe there is no way for modules to detect mouse clicks without video output being present. The plugin detects mouse clicks by implementing a video filter module interface of VLC, which tells it when and where a mouse click was done on the video output surface. If the file you play is audio-only, VLC doesn't load any video-related modules, so the video filter module doesn't get loaded and the plugin is unable to detect mouse clicks. So as far as I know it's not possible.
