### ISSUE TITLE
Intalling on debian Buster

### ISSUE THREAD

**Issue by Hux40** [nurupo/vlc-pause-click-plugin#61]
Hello,
Error during make statement.
Here is the error in the console:
~/vlc-pause-click-plugin$ make
cc -std=gnu99 -g0 -O3 -Wall -Wextra -fPIC -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -DPIC -I. -Isrc -DMODULE_STRING=\"pause_click\"  -c -o pause_click.o pause_click.c
In file included from /usr/include/vlc/plugins/vlc_playlist.h:32,
                 from pause_click.c:37:
/usr/include/vlc/plugins/vlc_aout.h:205:31: error: expected ‘)’ before ‘==’ token
 static_assert(AOUT_CHANIDX_MAX == AOUT_CHAN_MAX, "channel count mismatch");
                               ^~~
                               )
In file included from pause_click.c:44:
vlc_interface-2.2.0-git.h: In function ‘pl_Get’:
vlc_interface-2.2.0-git.h:99:33: error: ‘struct intf_thread_t’ has no member named ‘p_parent’; did you mean ‘p_next’?
     return (playlist_t *)(intf->p_parent);
                                 ^~~~~~~~
                                 p_next
vlc_interface-2.2.0-git.h:100:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [<commande interne>: pause_click.o] Error 1

Hux40

**Comment by nurupo** [comment]
Please grab the latest version of the plugin. You seem to be trying to build an ancient version of vlc-pause-click-plugin that doesn't even support VLC 3.0.0.

**Comment by nurupo** [comment]
I assume this was resolved. Fell free to re-open the issue if it wasn't.
