### ISSUE TITLE
Doesn't work.. 

### ISSUE THREAD

**Issue by vesterlay** [nurupo/vlc-pause-click-plugin#63]
##### Self-troubleshooting

- [x] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and the issue still persists

##### Software

OS: Windows / Linux / macOS - 5.4.31-1-MANJARO 
VLC version: 3.0.8
VLC bitness: dunno
Plugin version: 2.1.0-1
Plugin bitness: dunno

##### Issue description
Doesn't work, but it appears that the plugin loads up correctly, fullscreen toggle is operational.

**Comment by nurupo** [comment]
Not sure what you meant by the fullscreen toggle.

Can you tell if both of checkboxes appeared in Settings? [This one](http://i.imgur.com/m9yF5Px.png) and also [this one](http://i.imgur.com/OZLqmI6.png). Do you have both of them checked?

**Comment by vesterlay** [comment]
I meant this fullscreen thingy you can bind in plugin settings. Anyway, I haven't checked the other option, that's why it hadn't work. Thanks for the help, sorry for inconvenience :)
