### ISSUE TITLE
Plugin disfunctional on every VLC update?

### ISSUE THREAD

**Issue by stonecrusher** [nurupo/vlc-pause-click-plugin#69]
Hi
Just wanted to know if there's something wrong on my system or if it's normal.
I don't remember when it started, but at least on the latest four VLC updates the plugin function broke and I had to reinstall it.

The plugin dll didn't change for the different VLC versions and it was still in the correct folder.

So maybe another issue of #32 ?

VLC 64bit
Win10x64 v1909

**Comment by nurupo** [comment]
>and it was still in the correct folder

Are you sure that the plugin was still present in `{VLC}\plugins\video_filter\` after the update? I thought that VLC updates essentially re-installed everything, removing all previously existing files, so the dll would be gone. I don't use Windows often, will need to check this later when I'm near a Windows PC.

**Comment by stonecrusher** [comment]
> Are you sure that the plugin was still present
Not 100%, but I just ran a test in a VM and can confirm that this is the behaviour when updating from VLC 3.0.9.2 to 3.0.11.0 on a Win8.1x64 machine. But in that case I could "fix" it by just restarting VLC as recommended (the "open after installation" in the setup apparently doesn't count). That was not the case for my Win10 system.

> I thought that VLC updates essentially re-installed everything
Well, if you install you have the choice between clean reinstall and update (keep settings). Of course you don't want to sacrifice your settings on each update.

**Comment by stonecrusher** [comment]
I couldn't reproduce on another Win10 machine.
I guess it had something to do with having x64 and x32 versions installed on the same machine (one via faulty package manager).
However it seems like a problem with the VLC installer, not with the plugin.
I'll see how the next update on this machine works and report back. But apparently it's not a general problem, others would have had it, too.

**Comment by nurupo** [comment]
Got to test it on Windows 10 with 64-it VLC 3.0.8, updating it to 3.0.11, keeping the existing settings. The plugin has remained in the `{VLC}\plugins\video_filter\` directory and worked right away. Not sure why I remember the dll getting removed and having to re-install it before, perhaps I'm misremembering or VLC has changed the way it re-installs so it keeps unknown plugins now.

**Comment by stonecrusher** [comment]
Happened again with 3.0.14 update.
Plugin was not present anymore in the directory.
Maybe it's something with the windows filesystem rights management.
Did not try to reproduce in VM yet.
