### ISSUE TITLE
More detailed Linux installation instructions (for newbies like myself...)

### ISSUE THREAD

**Issue by cdokos** [nurupo/vlc-pause-click-plugin#73]
## Describe the issue

I think it would save Linux and git newbies (like myself) a lot of time and frustration if you included more detailed (git and make) instructions for building the plugin in the main Documentation (instead of providing it for individual requests, like you did in 2017 https://github.com/nurupo/vlc-pause-click-plugin/issues/28#issuecomment-352234793)

**Comment by adamsigal** [comment]
I completely agree with you. Why don't you add it yourself and make a pull request?

**Comment by nurupo** [comment]
Sorry, I have somehow missed this issue.

Sure, I can add such instructions, it makes sense for this repo to be a bit newbie friendly. I don't think there are any `make` instructions omitted though, are there? It's mostly `git` that is omitted (or you could alternatively download a release tarball).

**Comment by nurupo** [comment]
Should be fixed by https://github.com/nurupo/vlc-pause-click-plugin/commit/9d859ceecc95f0886be7865baef2693275438822.
