### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mtst99** [nurupo/vlc-pause-click-plugin#75]
## Checklist

- [ ] I have followed the [Usage section](https://github.com/nurupo/vlc-pause-click-plugin#usage) thoroughly, checking every single screenshot.
- [ ] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and it didn't solve my issue.

## Environment

- OS:               
- VLC version:      
- VLC bitness:      
- Plugin version:   
- Plugin bitness:

**Comment by mtst99** [comment]
Doesn't work on left click on vlc version 3011

**Comment by nurupo** [comment]
Sorry, can't help you. You have left the entire issue form empty. Please go over the checklist items and add the environment information.

**Comment by mtst99** [comment]
If it works then no problem its just me. have a good day.

**Comment by nurupo** [comment]
Huh.
