### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Perkin5** [nurupo/vlc-pause-click-plugin#8]
I'm not a programmer so I need a simple instruction on which file to put in which VLC directory. So far I've been unable to make it work on VLC 2.2. The existing Readme meant little to me.

Can you help - or will this be beyond a punter?

**Comment by nurupo** [comment]
What OS do you use and is your VLC 32 bit or 64 bit?

**Comment by Perkin5** [comment]
Wow - brilliant speed of response!

Windows 7 64-bit and VLC is also 64-bit

In the meantime I found your github page
https://github.com/nurupo/vlc-pause-click-plugin/blob/master/vlc-2.2.x%2B/README.md

and downloaded the correct version of *libpause_click_plugin.dll.*

It shows up in VLC and the Interface preferences checkbox is 
checked/saved/restarted but the click response is still not working.

Do I have to restart Windows?

Mike

**Comment by nurupo** [comment]
[There are two check boxes that you need to check](https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x%2B#usage). The interface one is just one of them.

**Comment by Perkin5** [comment]
You are quite rightand I didn't read the instructions carefully enough.

Thank you so much for your help and click/pause now works like a charm.

**Comment by nurupo** [comment]
Glad to hear.
