### ISSUE TITLE
Where to place plugin for a flatpak-installed VLC?

### ISSUE THREAD

**Issue by mrandreastoth** [nurupo/vlc-pause-click-plugin#84]
## Checklist

- [ x] I have followed the [Usage section](https://github.com/nurupo/vlc-pause-click-plugin#usage) thoroughly, checking every single screenshot.
- [ x] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and it didn't solve my issue.

## Environment

- OS: Zorin OS 16
- VLC version: 3.0.16
- VLC bitness: 64-bit (I think!)
- Plugin version: 2.2.0
- Plugin bitness:  64-bit

## Describe the issue

I've tried installing the plugin using the make file but VLC doesn't pick it up. I have tried manually copying the plugin to various other locations including various directories and sub-directories under ~/.var/app/org.videolan.VLC/data/vlc. This has included adding a "plugins" directory to these locations and placing the plugin in these directories. Nothing has worked. Perhaps I needed to change the file/directory permissions, I don't know.

**Comment by nurupo** [comment]
Actually no idea, haven't used Flatpak VLC, using VLC packaged by my distro.

Looking at the [Flatpak VLC repository](https://github.com/flathub/org.videolan.VLC), it says that one should create a separate Flatpak for a plugin to be able to use it with Flatpak VLC:

>To package independent plugins for VLC you can create an extension org.videolan.VLC.Plugin.myplugin.

So I guess you won't be able to use the plugin unless someone makes a Flatpak of it?

If you are able to add files to the Flatpak (honestly no idea how Flatpak works, I don't think you should be able to add files to it, yet you are saying that you are somehow able to so, so I'm just rolling with it), you could find the existing "plugins" directory in it (VLC is pretty much a bunch of plugins) and place `libpause_click_plugin.so` in there. It should work, as long as the plugin you built on your system is compatible ABI-wise with the environment used to build and run the Flatpak VLC.

**Comment by mrandreastoth** [comment]
> Actually no idea, haven't used Flatpak VLC, using VLC packaged by my distro.

Unfortunately my distro supports a handful of package managers, including Flatpak, which I've since have found out are a bad idea as its packages are bloated and can carry outdated libraries. I also dislike the horrible command-line in just trying to run an installed binary, shocking syntax, I'm not sure who thought it a good idea. As such I'm going to uninstall all my Flatpak packages and replace them with something better and more manageable.

P.S. I've also decided to no longer use VLC as I had numerous issues with it, including responsiveness and the fact that subtitles don't update while paused meaning synchronising them is a pain in the rear (the best way to synchronise subtitles is to pause them just where speech is started then decrease/increase the subtitle delay until they appear). As such, I'm now using SMPlayer.

**Comment by n3m0-22** [comment]
In case anyone else is having this issue. If you add the file `libpause_click_plugin.so` to the directory `local/share/flatpak/app/org.videolan.VLC/x86_64/stable/e737adfbdb87e287835209fb7defc1ecfe71974adbfec6fadead7c5699e72a83/files/lib/vlc/plugins/control/` it will work with the Flatpak. 

Note: The `e737adfbdb87e287835209fb7defc1ecfe71974adbfec6fadead7c5699e72a83` part of this directory may not be exactly the same you'll will need to check.

**Comment by nurupo** [comment]
Just an update that the plugin is now available on Flathub and can be installed in one command. See https://github.com/nurupo/vlc-pause-click-plugin#flatpak
