### ISSUE TITLE
OS X download links don't work

### ISSUE THREAD

**Issue by colin-marshall** [nurupo/vlc-pause-click-plugin#9]
The OS X download links on this page are broken: https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x%2B

**Comment by nurupo** [comment]
Thanks for pointing this out. Apparently I used the wrong version number for the tag release, 2.0.1 instead of 0.2.1. Will fix sometime within 24h. For now you can get the OS X  binary from [the release page](https://github.com/nurupo/vlc-pause-click-plugin/releases/tag/2.0.1).

**Comment by nurupo** [comment]
Fixed.
