### ISSUE TITLE
Update to pluging directory placement

### ISSUE THREAD

**Issue by Matthew-Hiebing** [nurupo/vlc-pause-click-plugin#91]

**Comment by nurupo** [comment]
There is nothing to update, README does say to install it into the plugins directory:

>Extract the archive at `{VLC}\plugins\video_filter\`, where `{VLC}` is the directory the VLC was installed into.
>
>By default, the 32-bit VLC installs into `C:\Program Files (x86)\VideoLAN\VLC\` and the 64-bit one into `C:\Program Files\VideoLAN\VLC\`.

Perhaps it could be better worded? What wording would you suggest that would make the instructions clearer?

**Comment by Matthew-Hiebing** [comment]
You are right!  I misread the first section where it says, `{VLC}\plugins\video\vide_filter\`.  My mistake!

**Comment by Matthew-Hiebing** [comment]
No change needed.
