### ISSUE TITLE
Does not show up in Ubuntu 22.04 / VLC 3.0.18

### ISSUE THREAD

**Issue by victorkitov** [nurupo/vlc-pause-click-plugin#96]
## Checklist

- [ x] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and the issue still persists.

## Environment

- OS:               Ubuntu 22.04 
- VLC version:      3.0.18
- VLC bitness:      64bit
- Plugin version:   vlc-pause-click-plugin-2.2.0
- Plugin bitness:   ?? default ubuntu snap-store install on 64bit system. 

## Describe the bug

After completing Debian installation steps (tried both through git and making of tarball) & restart of VLC (and ever restart of PC) no change in VLC interface - cannot find options to utilize the plug-in. 

1) [Preferences]->[Show settings]->[All]
2) [Preferences]->[Control interfaces]: there is no option "Pause play on mouse click".

**Comment by nurupo** [comment]
>default ubuntu snap-store install on 64bit system.

Is that a Snap VLC by any chance?

**Comment by victorkitov** [comment]
I suppose yes. It's installed to /snap/bin/vlc.

**Comment by nurupo** [comment]
See https://github.com/nurupo/vlc-pause-click-plugin#snap

**Comment by victorkitov** [comment]
I see, thank you. Then the issue is closed.

**Comment by nurupo** [comment]
I suggest using non-Snap VLC, e.g. from the package repository or Flathub - the plugin works with those.

**Comment by victorkitov** [comment]
After removing VLC from Ubuntu Software (snap installation) and reinstalling VLC using `sudo apt install vlc` the plugin works like charm. Thanks!

**Comment by hoangngo-calvin** [comment]
This question is so helpful. Thanks
